version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.6.11
      
    working_directory: ~/repo

    steps:
      - checkout
      
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install 
      
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint